Roaring64NavigableMap equals Bug + Leak
RoaringBitmap/RoaringBitmap pull request #453
Opened 2021-02-04 08:26 UTC by Maithem

This patch removes the key(high part) from highToBitmap when
the corresponding BitmapDataProvider becomes empty after a
removeLong call. This prevent memory leaks and fixes the equality
check when some mappings are empty but not removed from the map.

2021-02-04 08:26 UTC, Maithem commented
Fixes #452

2021-02-04 08:38 UTC, blacelle commented
While the code looks OK, a unit-test complains:

```
TestRoaring64NavigableMap > testRemove_Signed() FAILED
    org.opentest4j.AssertionFailedError at TestRoaring64NavigableMap.java:435
```

2021-02-04 08:47 UTC, Maithem commented
> While the code looks OK, a unit-test complains:
> 
> ```
> TestRoaring64NavigableMap > testRemove_Signed() FAILED
>     org.opentest4j.AssertionFailedError at TestRoaring64NavigableMap.java:435
> ```

Yep, still looking into it. I think there's a bug. Only removing the key from the map is not enough, I need to readjust a couple more variables like firstHighNotValid, latestAddedHigh, etc.

2021-02-04 09:06 UTC, blacelle commented
Thanks @Maithem I can have a deeper look if useful / the fix is not easy.

2021-02-04 09:29 UTC, Maithem commented
> Thanks @Maithem I can have a deeper look if useful / the fix is not easy.

I fixed the bug and CI seems to be passing. Would appreciate a review. Thanks!

2021-02-04 09:39 UTC, blacelle commented
It looks good to me. We may benefit from a specific unit-test reproducing the bug you may have introduced. I feel something like:

  @Test
  public void testNotEmptyAfterRemote() {
    Roaring64NavigableMap rbm = new Roaring64NavigableMap();
    rbm.addLong(1L);
    assertEquals(rbm.getHighToBitmap().size(), 1);
    rbm.addLong(Integer.MAX_VALUE + 1L);
    assertEquals(rbm.getHighToBitmap().size(), 2);
    rbm.removeLong(Integer.MAX_VALUE + 1L);
    assertEquals(rbm.getHighToBitmap().size(), 1);
    
    assertEquals(rbm.getLongIterator().next(), 1L);
  }

would have reproduced it specifically.

2021-02-04 21:25 UTC, lemire commented
@Maithem Would you consider adding a test as suggested by @blacelle ?

2021-02-10 07:17 UTC, blacelle requested changes
Please add the provided unit-test. I ensured it reproduce the case of potential bug.

2021-02-11 03:47 UTC, Maithem commented
@blacelle ok, adopted your suggestion. I resisted accessing private class fields because it makes it hard to use the same test for a different implementation and its not general.

2021-02-11 08:21 UTC, blacelle commented
@Maithem Sorry for the noise. But I feel you should have kept your initial test, in addition of mine. These are 2 edge-case: the first removes a bucket getting empty, the second removes bucket remaining non-empty.

Just keep the 2 tests, and I'll approve right away.

2021-02-11 17:50 UTC, Maithem commented
@blacelle no worries, I thought you meant to combine the tests. Anyways, added both tests now.

2021-02-11 18:21 UTC, blacelle approved these changes

2021-02-11 18:23 UTC, lemire commented
Merging.

2021-02-11 18:23 UTC, merged