Optimized creation of bitmap by range
RoaringBitmap/RoaringBitmap pull request #686
Opened 2023-11-09 18:38 UTC by xtonik

### SUMMARY
Optimized creation of bitmap by range via factory method `Util.bitmapOf()`. There is a trade-off between performance and  code is  duplication, but it can be ignored as piece of duplicated code is already duplicated several times in class `RoaringBitmap`.

| Benchmark | (offset) | (bytes) | Mode | Cnt | Score | Error | Units | 
| --- | --- | --- | --- | --- | --- | --- | --- |
| optimized | 0 | 10 | avgt | 5 | 31.364 | ±0.964 | ns/op |
| optimized | 0 | 100000 | avgt | 5 | 45.240 | ±3.783 | ns/op |
| optimized | 0 | 10000000 | avgt | 5 | 1663.824 | ±22.388 | ns/op |
| optimized | 100000 | 10 | avgt | 5 | 31.179 | ±0.358 | ns/op |
| optimized | 100000 | 100000 | avgt | 5 | 59.337 | ±9.726 | ns/op |
| optimized | 100000 | 10000000 | avgt | 5 | 1764.398 | ±329.763 | ns/op |
| original | 0 | 10 | avgt | 5 | 40.100 | ±1.431 | ns/op |
| original | 0 | 100000 | avgt | 5 | 65.978 | ±9.748 | ns/op |
| original | 0 | 10000000 | avgt | 5 |  3338.978 | ±379.935 | ns/op |
| original | 100000 | 10 | avgt | 5 | 40.919 | ±3.560 | ns/op |
| original | 100000 | 100000 | avgt | 5 | 84.212 | ±1.339 | ns/op |
| original | 100000 | 10000000 | avgt | 5 | 3295.778 | ±68.212 | ns/op |

Some tests added to verify correctness and improve code coverage.

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

2023-11-17 22:42 UTC, lemire commented
Can you explain why it is faster? Didn't you just inline the original code...

```Java
     RoaringBitmap bitmap = new RoaringBitmap();
     bitmap.add(min, max);
```

???

I am concerned that the benchmark might be misleading.

2023-11-25 11:08 UTC, xtonik commented
The main difference is that unnecessary copying of arrays in method [`RoaringArray#insertNewKeyValueAt(int, char, Container)`](https://github.com/RoaringBitmap/RoaringBitmap/blob/8dd4a5ec22531704ab834db66af89804c17fe37e/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringArray.java#L794) is avoided using method [RoaringBitmap#append(char, Container)](https://github.com/RoaringBitmap/RoaringBitmap/blob/8dd4a5ec22531704ab834db66af89804c17fe37e/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L3104) instead of. Above that resizing of RoaringArray is avoided also as it is precisely allocated beforehand.

Can you be more specific about misleading benchmark?

2024-01-27 14:42 UTC, lemire commented
Thanks for the analysis. It makes sense.

Can you provide the same optimization to the buffer package? (E.g., producing a MutableRoaringBitmap).

2024-01-27 14:44 UTC, lemire requested changes
We should either explain why this optimization does not apply to the buffer package (e.g., producing MutableRoaringBitmap), or we should provide it.

2024-01-27 19:09 UTC, xtonik commented
Version for buffered bitmap added.

2024-01-28 17:07 UTC, lemire approved these changes

2024-01-28 17:07 UTC, lemire commented
Merging.

2024-01-28 17:07 UTC, merged