Method fillArray() deduplicated
RoaringBitmap/RoaringBitmap pull request #707
Opened 2024-01-21 03:15 UTC by xtonik

### SUMMARY
Methods `fillArray()` deduplicated, part for processing buffered input removed completely as it was dead code.

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

2024-01-27 14:26 UTC, lemire requested changes
The reason we have a complicated fillArray method that checks BufferUtil.isBackedBySimpleArray is that doing `bitmap.array()` can be expensive when the `bitmap` instance is not backed by an array. Your PR seems to lose this optimization. Now, it might be fine, but you should document first that it does not negatively impact the performance *when the bitmap is not backed by an array*.

2024-01-27 16:10 UTC, xtonik commented
It was impossible to execute branch for mapped arrays and it was possible after the method had been reused. Above that, I there is [condition to avoid this situation](https://github.com/RoaringBitmap/RoaringBitmap/pull/707/commits/bb5eb082497a2a9af159c74785bb48fb5ab0a0ed#diff-7030071ad402f246b75f939e786431cba04b863f8c10530ceb7e622efcaaea5bL1041), which contradicts with original implementation.

2024-01-28 17:03 UTC, lemire approved these changes

2024-01-28 17:03 UTC, lemire commented
Makes sense. Merging.

2024-01-28 17:04 UTC, merged