Move instance field to static
RoaringBitmap/RoaringBitmap pull request #714
Opened 2024-03-22 04:38 UTC by DanielThomas

### SUMMARY

This adds an additional unnecessary reference to every `BitmapContainer`.

### Automated Checks

- [ x ] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [ x ] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

2024-03-22 04:40 UTC, lemire commented
Looks like a good catch.

2024-03-22 04:41 UTC, lemire commented
@DanielThomas Could you also do: https://github.com/RoaringBitmap/RoaringBitmap/blob/dda04be1c1ff514b94875499476825daba4ed3dc/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java#L55

2024-03-22 05:38 UTC, DanielThomas commented
@lemire I removed some duplication and switched in some size constants. Do you mind the cross-cutting package imports?

2024-03-22 05:52 UTC, DanielThomas commented on RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
> +    int sizeAsBitmapContainer = serializedSizeInBytes(0);
Oops, let me fix this.

2024-03-22 08:41 UTC, richardstartin approved these changes
I guess nobody ever spotted this because bitmap containers contain an 8KiB array, so if you have enough of them for this slip up to show up noticeably, you would be distracted by hundreds of MiBs or even GiBs of `long[]` in the heap dump, but this is a great catch.

2024-03-22 08:52 UTC, DanielThomas commented
YourKit's duplicate object inspection :)

2024-03-22 14:14 UTC, lemire commented
@DanielThomas Can you check the CI logs? I see...

```

  symbol:   variable MAX_CAPACITY
  location: class MappeableBitmapContainer
/home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferBitSetUtil.java:24: error: cannot find symbol
  static final private int BLOCK_LENGTH = MappeableBitmapContainer.MAX_CAPACITY / Long.SIZE; //
                                                                  ^
```

2024-04-18 13:19 UTC, lemire commented
@DanielThomas This PR still does not build...

```
/home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java:1165: warning: [deprecation] MutableRoaringBitmapPrivate in org.roaringbitmap.buffer has been deprecated
        MutableRoaringBitmapPrivate.repairAfterLazy((MutableRoaringBitmap) lowBitmap);
        ^
/home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java:185: error: cannot find symbol
      bitmapArray.limit(MappeableBitmapContainer.MAX_CAPACITY / 64);
                                                ^
  symbol:   variable MAX_CAPACITY
  location: class MappeableBitmapContainer
/home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferBitSetUtil.java:24: error: cannot find symbol
  static final private int BLOCK_LENGTH = MappeableBitmapContainer.MAX_CAPACITY / Long.SIZE;
```

2024-04-20 06:57 UTC, DanielThomas commented
Sorry @lemire, let me get that fixed.

2024-04-22 01:40 UTC, DanielThomas commented
Based on your comments on the other PR about code duplication being a thing, I've rolled back any other changes and restricted this to making the field in `BitmapContainer` static.

2024-04-22 15:02 UTC, lemire commented
> Based on your comments on the other PR about code duplication being a thing for the project, I've rolled back any other changes and restricted this to making the field in BitmapContainer static.

Note that it is not that we encourage code duplication;  it is merely that, historically, we have accepted it **in this library**.

I do not discourage you from removing unnecessary code duplication. However, I prefer to be prudent with code refactoring that merely reduces code duplication because we can introduce new bugs by mistake.

2024-04-22 15:09 UTC, lemire requested changes
We try to keep in sync BitmapContainer.java and MappeableBitmapContainer.java. Could you apply your changes to MappeableBitmapContainer.java.

See...


https://github.com/RoaringBitmap/RoaringBitmap/blob/5235aa62c32fa3bf7fae40a562e3edc75f61be4e/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java#L55

2024-06-17 12:43 UTC, lemire commented
Extended, see https://github.com/RoaringBitmap/RoaringBitmap/pull/726

2024-06-18 13:08 UTC, lemire commented
@DanielThomas You have credit in PR https://github.com/RoaringBitmap/RoaringBitmap/pull/726 where I extended this work.

2024-06-18 13:08 UTC, closed without merging